"""Resource defaults derived from declared dependencies (GPU inference)."""

from __future__ import annotations

import json
import os
import re
import sys
import tomllib
from itertools import chain
from pathlib import Path

# import name -> pip install name, for the few mismatches; every other
# import installs under its own name (identity fallback in _pip_name)
KNOWN_PACKAGES = {
    "sklearn": "scikit-learn",
    "skimage": "scikit-image",
    "PIL": "Pillow",
    "cv2": "opencv-python",
    "yaml": "PyYAML",
}

# pip install name -> import name (reverse of KNOWN_PACKAGES, plus the
# torch alias); used by the env-reuse validation to probe existing conda
# environments. Unmapped names are skipped by the probe, not guessed.
IMPORT_BY_PIP = {
    **{pip_name: import_name for import_name, pip_name in KNOWN_PACKAGES.items()},
    "pytorch": "torch",  # the pip alias installs the `torch` module
}

REQUIREMENTS_HEADER = "# generated by lazy107 env: packages detected from code imports"

_STDLIB = sys.stdlib_module_names

# Frameworks that imply GPU acceleration; any of them upgrades a project
# to the GPU resource profile in derive_defaults.
GPU_PACKAGES = frozenset(
    [
        "flax",
        "jax",
        "jaxlib",
        "keras",
        "pytorch",
        "tensorflow",
        "tf-keras",
        "torch",
        "torchaudio",
        "torchvision",
    ]
)

# torch-family subset used for CUDA build verification and pip overrides
TORCH_PACKAGES = frozenset(["torch", "pytorch", "torchvision", "torchaudio"])

# High-confidence DDP signals, anchored to import/usage forms so docstrings and
# comments cannot trigger a torchrun launch (a false positive would run the
# entry N times under torchrun instead of once).
DDP_PATTERNS = (
    re.compile(r"^\s*(import|from)\s+torch\.distributed\b"),
    re.compile(r"^\s*from\s+torch\.nn\.parallel\s+import\s+\bDistributedDataParallel\b"),
    re.compile(r"\bDistributedDataParallel\s*\("),
    re.compile(r"\binit_process_group\s*\("),
    re.compile(r"^\s*(import|from)\s+accelerate\b"),
    re.compile(r"^\s*(import|from)\s+deepspeed\b"),
    re.compile(r"strategy\s*=\s*[\"']ddp"),
    re.compile(r"\bddp_find_unused_parameters\s*="),
)


def _extract_package_names(text: str) -> set[str]:
    names: set[str] = set()
    for line in text.splitlines():
        line = line.split("#", 1)[0].strip()
        match = re.match(r"^([\w.-]+)", line)
        if match:
            names.add(match.group(1).lower().replace("_", "-"))
    return names


def _read_requirements(path: Path) -> set[str]:
    if not path.exists():
        return set()
    return _extract_package_names(path.read_text(encoding="utf-8"))


def _read_pyproject_dependencies(path: Path) -> set[str]:
    if not path.exists():
        return set()
    try:
        data = tomllib.loads(path.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError):
        return set()
    project = data.get("project", {})
    sources = chain(
        project.get("dependencies", []),
        *(group for group in project.get("optional-dependencies", {}).values()),
    )
    return {name for dep in sources for name in _extract_package_names(dep)}


def _read_environment_yml(path: Path) -> set[str]:
    if not path.exists():
        return set()
    names: set[str] = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        match = re.match(r"^\s*-\s+([A-Za-z0-9_.-]+)", line)
        if match:
            names.add(match.group(1).lower().replace("_", "-"))
    return names


def _scan_line(line: str) -> set[str]:
    """Top-level module names from an import line (possibly comma-separated)."""
    line = line.split("#", 1)[0].strip()
    if line.startswith("import "):
        names: set[str] = set()
        for part in line[len("import ") :].split(","):
            words = part.split()
            if not words:  # empty segment: `import torch,` or a bare `import `
                continue
            name = words[0].split(".")[0]
            if name:
                names.add(name)
        return names
    if line.startswith("from "):
        words = line[len("from ") :].split()
        if not words:
            return set()
        name = words[0].split(".")[0]
        return {name} if name else set()  # relative imports (from . import x) yield ''
    return set()


def _pip_name(name: str) -> str:
    """pip install name for an import name; identity unless a known mismatch."""
    return KNOWN_PACKAGES.get(name, name)


def _code_lines(path: Path) -> list[str]:
    """Lines to scan: the whole file for .py, code cells for .ipynb; [] when unreadable."""
    try:
        text = path.read_text(encoding="utf-8-sig")  # sig: strip BOM on line 1
    except (OSError, UnicodeDecodeError):  # non-UTF-8 (e.g. GBK) files are skipped, not fatal
        return []
    if path.suffix != ".ipynb":
        return text.splitlines()
    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        return []
    lines: list[str] = []
    for cell in data.get("cells", []):
        if cell.get("cell_type") == "code":
            lines.extend(cell.get("source", []))
    return lines


def _ignore_walk_error(_error: OSError) -> None:
    """Skip directories that cannot be listed (permissions, broken mounts)."""


def _project_code_files(project_root: Path) -> list[Path]:
    """*.py and *.ipynb files outside hidden directories (e.g. .venv, .git)."""
    files: list[Path] = []
    for root, dirs, names in os.walk(project_root, onerror=_ignore_walk_error):
        dirs[:] = [d for d in dirs if not d.startswith(".")]
        for name in names:
            if name.endswith((".py", ".ipynb")):
                path = Path(root) / name
                if path.is_file():
                    files.append(path)
    return files


def scan_imports(project_root: Path) -> set[str]:
    """pip install names for third-party imports found in the project's code.

    Stdlib imports and the project's own modules are skipped; hidden directories
    (e.g. .venv, .git) are not scanned; unreadable or non-UTF-8 files are ignored;
    notebooks contribute their code cells. Docstring lines that look like imports
    are an accepted false-positive risk (extra install, never a wrong resource).
    """
    local: set[str] = set()
    files = _project_code_files(project_root)
    for path in files:
        if path.name == "__init__.py":
            local.add(path.parent.name)
        elif path.suffix == ".py":
            local.add(path.stem)
    packages: set[str] = set()
    for path in files:
        for line in _code_lines(path):
            for name in _scan_line(line):
                if name in _STDLIB or name in local:
                    continue
                packages.add(_pip_name(name))
    return packages


def detect_ddp(project_root: Path) -> bool:
    """True when the project code signals distributed data parallel training.

    Only high-confidence forms count (import lines and known call/option
    patterns); a false positive would launch the entry N times under
    torchrun, so bare mentions in comments/docstrings are ignored.
    """
    for path in _project_code_files(project_root):
        for line in _code_lines(path):
            line = line.split("#", 1)[0].strip()  # comments must never trigger a torchrun launch
            if any(p.search(line) for p in DDP_PATTERNS):
                return True
    return False


def detect_dependencies(project_root: Path) -> set[str]:
    deps: set[str] = set()
    deps |= _read_pyproject_dependencies(project_root / "pyproject.toml")
    deps |= _read_requirements(project_root / "requirements.txt")
    deps |= _read_environment_yml(project_root / "environment.yml")
    deps |= scan_imports(project_root)
    return deps


def write_requirements(project_root: Path, packages: set[str]) -> Path:
    """Write detected packages to requirements.txt (user-editable afterwards)."""
    path = project_root / "requirements.txt"
    content = REQUIREMENTS_HEADER + "\n" + "\n".join(sorted(packages)) + "\n"
    path.write_text(content, encoding="utf-8")
    return path


def has_gpu_dependency(deps: set[str]) -> bool:
    return bool(deps & GPU_PACKAGES)


def derive_defaults(project_root: Path) -> dict[str, object]:
    """Return resource defaults; GPU workloads get 1 GPU / 4 CPU / 16G / 2h."""
    if has_gpu_dependency(detect_dependencies(project_root)):
        return {"gpu": 1, "cpus": 4, "mem": "16G", "time": "2:00:00"}
    return {"gpu": 0, "cpus": 2, "mem": "4G", "time": "1:00:00"}
