"""Config merge: 4 layers (defaults < derived < global < project < env/flags)."""

from __future__ import annotations

import os
import re
import tomllib
from dataclasses import fields
from pathlib import Path

from lazy107.core.plan import RunPlan

MANIFEST_NAME = "107.toml"

_FIELD_KEYS = tuple(f.name for f in fields(RunPlan) if f.name != "effective_job_name")


def global_config_path() -> Path:
    """Per-user global config: ~/.config/lazy107/config.toml."""
    return Path.home() / ".config" / "lazy107" / "config.toml"


def load_manifest(project_root: Path) -> dict:
    """Values from the project's 107.toml (flat keys or [run] section); {} when absent."""
    path = project_root / MANIFEST_NAME
    if not path.exists():
        return {}
    with path.open("rb") as fh:
        data = tomllib.load(fh)
    section = data.get("run")
    return section if isinstance(section, dict) else data


def load_global() -> dict:
    """Values from the per-user global config; {} when absent or invalid."""
    path = global_config_path()
    if not path.exists():
        return {}
    try:
        with path.open("rb") as fh:
            data = tomllib.load(fh)
    except (OSError, tomllib.TOMLDecodeError):
        return {}
    return {k: v for k, v in data.items() if k in _FIELD_KEYS}


def _coerce(key: str, raw: str):
    return int(raw) if key in {"cpus", "gpu", "nodes", "ntasks"} else raw


def resolve_plan(
    project_root: Path,
    flags: dict | None = None,
    derived: dict | None = None,
) -> RunPlan:
    """Merge RunPlan defaults < dependency-derived < global config < 107.toml < LAZY107_* env < flags."""
    values: dict = {}
    if derived:
        values.update(derived)
    global_cfg = load_global()
    for key in _FIELD_KEYS:
        value = global_cfg.get(key)
        if value is not None:
            values[key] = value
    manifest = load_manifest(project_root)
    for key in _FIELD_KEYS:
        if manifest.get(key) is not None:
            values[key] = manifest[key]
    for key in _FIELD_KEYS:
        raw = os.environ.get(f"LAZY107_{key.upper()}")
        if raw not in (None, ""):
            values[key] = _coerce(key, raw)
    for key, val in (flags or {}).items():
        if val is not None and key in _FIELD_KEYS:
            values[key] = val
    return RunPlan(**values)


def entry_path(project_root: Path, entry: str) -> Path:
    """Absolute entry path; raises FileNotFoundError when missing."""
    path = (project_root / entry).resolve()
    if not path.is_file():
        raise FileNotFoundError(f"entry not found: {path}")
    return path


def wire_entry(project_root: Path, entry: str) -> str:
    """Ensure 107.toml sets `entry = "<entry>"`, replacing an existing pin.

    entry is already a forward-slash path relative to project_root and is
    free of quotes/backslashes (the interactive picker rejects those), so
    the TOML string needs no escaping. Returns a human-readable status
    line for the caller to print.
    """
    path = project_root / MANIFEST_NAME
    data = load_manifest(project_root)
    line = f'entry = "{entry}"'
    if path.exists():
        text = path.read_text(encoding="utf-8")
        if "entry" in data:
            # e.g. the `config --init` template ships `entry = ""`: replace, don't duplicate.
            text = re.sub(r"^\s*entry\s*=.*$", line, text, count=1, flags=re.MULTILINE)
        else:
            text = text.rstrip() + f"\n{line}\n"
        path.write_text(text, encoding="utf-8")
    else:
        path.write_text(
            f"# lazy107 project config (generated by `plan`)\n{line}\n",
            encoding="utf-8",
        )
    return f"pinned entry = {entry!r} in {MANIFEST_NAME}"


def wire_fields(project_root: Path, updates: dict) -> str:
    """Ensure 107.toml sets each key to the given value, replacing existing keys.

    Standalone from wire_entry/wire_conda_env (those carry keep/force
    semantics); used by the `everything` wizard to pin Slurm params the
    user edited. Values come straight from the interactive editor (ints
    for gpu/cpus, plain safe strings for mem/time), so the TOML lines
    need no escaping. Returns a human-readable status line to print.
    """
    path = project_root / MANIFEST_NAME
    text = path.read_text(encoding="utf-8") if path.exists() else ""
    for key, value in updates.items():
        line = f'{key} = "{value}"' if isinstance(value, str) else f"{key} = {value}"
        pattern = rf"^\s*{re.escape(key)}\s*=.*$"
        if re.search(pattern, text, flags=re.MULTILINE):
            text = re.sub(pattern, line, text, count=1, flags=re.MULTILINE)
        elif text:
            text = text.rstrip("\n") + f"\n{line}\n"
        else:
            text = f"{line}\n"
    if not path.exists():
        text = f"# lazy107 project config (generated by `everything`)\n{text}"
    path.write_text(text, encoding="utf-8")
    keys = ", ".join(f"{key}={value!r}" for key, value in updates.items())
    return f"wired {keys} into {MANIFEST_NAME}"


def wire_conda_env(project_root: Path, env_name: str, force: bool = False) -> str:
    """Ensure 107.toml sets `conda_env = "<env_name>"`.

    Without `force`, a non-empty existing value is kept (env creation
    flow). With `force`, an existing value is replaced — used when the
    user picks an existing env to reuse and the project must switch to it.

    env_name comes from cluster.env.env_name_for, which sanitizes to
    [A-Za-z0-9_.-]+, so the TOML string needs no escaping. Returns a
    human-readable status line for the caller to print.
    """
    path = project_root / MANIFEST_NAME
    data = load_manifest(project_root)
    existing = data.get("conda_env")
    if existing and (not force or existing == env_name):
        return f"kept conda_env = {existing!r} already set in {MANIFEST_NAME}"
    line = f'conda_env = "{env_name}"'
    if path.exists():
        text = path.read_text(encoding="utf-8")
        if "conda_env" in data:
            # e.g. the `config --init` template ships `conda_env = ""`: replace, don't duplicate.
            text = re.sub(r"^\s*conda_env\s*=.*$", line, text, count=1, flags=re.MULTILINE)
        else:
            text = text.rstrip() + f"\n{line}\n"
        path.write_text(text, encoding="utf-8")
    else:
        path.write_text(
            f"# lazy107 project config (generated by `env --yes`)\n{line}\n",
            encoding="utf-8",
        )
    return f"wired conda_env = {env_name!r} into {MANIFEST_NAME}"
